// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emryofyuawtlhdhjzorh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcnlvZnl1YXd0bGhkaGp6b3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjI1MTgsImV4cCI6MjA1Mjc5ODUxOH0.F2gxwqlfLIq6SFFdl9PYDvdelAou8cRmRAv_7e8WA8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);